src/Infrastructure/Fitness/Doctrine/Entity/Activity.php
<?php

namespace App\Infrastructure\Fitness\Doctrine\Entity;

use App\Infrastructure\Fitness\Repository\DoctrineActivityRepository;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Bridge\Doctrine\Types\UuidType;
use Symfony\Component\Uid\Uuid;

#[ORM\Entity(repositoryClass: DoctrineActivityRepository::class)]
class Activity
{
    /**
     * @var Uuid|null
     */
    #[ORM\Id]
    #[ORM\Column(type: UuidType::NAME, unique: true)]
    #[ORM\GeneratedValue(strategy: 'CUSTOM')]
    #[ORM\CustomIdGenerator(class: 'doctrine.uuid_generator')]
    private ?Uuid  $id = null;

    /**
     * @var string|null
     */
    #[ORM\Column(length: 255)]
    private ?string $activity_type = null;

    /**
     * @var \DateTimeInterface|null
     */
    #[ORM\Column(type: Types::DATETIME_MUTABLE)]
    private ?\DateTimeInterface $activity_date = null;

    /**
     * @var Uuid|null
     */
    #[ORM\Column(type: UuidType::NAME)]
    private ?Uuid $user_id = null;

    /**
     * @var float|null
     */
    #[ORM\Column]
    private ?float $distance = null;

    /**
     * @var string|null
     */
    #[ORM\Column(length: 255)]
    private ?string $distance_unit = null;

    /**
     * @var int|null
     */
    #[ORM\Column]
    private ?int $elapsed_time = null;

    /**
     * @return Uuid|null
     */
    public function getId(): ?Uuid
    {
        return $this->id;
    }

    /**
     * @return string|null
     */
    public function getActivityType(): ?string
    {
        return $this->activity_type;
    }

    /**
     * @param string $activity_type
     * @return $this
     */
    public function setActivityType(string $activity_type): static
    {
        $this->activity_type = $activity_type;

        return $this;
    }

    /**
     * @return \DateTimeInterface|null
     */
    public function getActivityDate(): ?\DateTimeInterface
    {
        return $this->activity_date;
    }

    /**
     * @param \DateTimeInterface $activity_date
     * @return $this
     */
    public function setActivityDate(\DateTimeInterface $activity_date): static
    {
        $this->activity_date = $activity_date;

        return $this;
    }

    /**
     * @return Uuid|null
     */
    public function getUserId(): ?Uuid
    {
        return $this->user_id;
    }

    /**
     * @param Uuid $user_id
     * @return $this
     */
    public function setUserId(Uuid $user_id): static
    {
        $this->user_id = $user_id;

        return $this;
    }

    /**
     * @return float|null
     */
    public function getDistance(): ?float
    {
        return $this->distance;
    }

    /**
     * @param float $distance
     * @return $this
     */
    public function setDistance(float $distance): static
    {
        $this->distance = $distance;

        return $this;
    }

    /**
     * @return string|null
     */
    public function getDistanceUnit(): ?string
    {
        return $this->distance_unit;
    }

    /**
     * @param string $distance_unit
     * @return $this
     */
    public function setDistanceUnit(string $distance_unit): static
    {
        $this->distance_unit = $distance_unit;

        return $this;
    }

    /**
     * @return int|null
     */
    public function getElapsedTime(): ?int
    {
        return $this->elapsed_time;
    }

    /**
     * @param int $elapsed_time
     * @return $this
     */
    public function setElapsedTime(int $elapsed_time): static
    {
        $this->elapsed_time = $elapsed_time;

        return $this;
    }

}

src/Infrastructure/Fitness/Doctrine/Entity/User.php
<?php

namespace App\Infrastructure\Fitness\Doctrine\Entity;

use App\Infrastructure\Fitness\Repository\UserRepository;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Bridge\Doctrine\Types\UuidType;
use Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface;
use Symfony\Component\Security\Core\User\UserInterface;
use Symfony\Component\Uid\Uuid;

#[ORM\Entity(repositoryClass: UserRepository::class)]
#[ORM\UniqueConstraint(name: 'UNIQ_IDENTIFIER_EMAIL', fields: ['email'])]
class User implements UserInterface, PasswordAuthenticatedUserInterface
{
    #[ORM\Id]
    #[ORM\Column(type: UuidType::NAME, unique: true)]
    #[ORM\GeneratedValue(strategy: 'CUSTOM')]
    #[ORM\CustomIdGenerator(class: 'doctrine.uuid_generator')]
    private ?Uuid $id = null;

    #[ORM\Column(length: 180)]
    private ?string $email = null;

    /**
     * @var list<string> The user roles
     */
    #[ORM\Column]
    private array $roles = [];

    /**
     * @var string The hashed password
     */
    #[ORM\Column]
    private ?string $password = null;

    public function getId(): ?Uuid
    {
        return $this->id;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): static
    {
        $this->email = $email;

        return $this;
    }

    /**
     * A visual identifier that represents this user.
     *
     * @see UserInterface
     */
    public function getUserIdentifier(): string
    {
        return (string) $this->email;
    }

    /**
     * @see UserInterface
     *
     * @return list<string>
     */
    public function getRoles(): array
    {
        $roles = $this->roles;
        // guarantee every user at least has ROLE_USER
        $roles[] = 'ROLE_USER';

        return array_unique($roles);
    }

    /**
     * @param list<string> $roles
     */
    public function setRoles(array $roles): static
    {
        $this->roles = $roles;

        return $this;
    }

    /**
     * @see PasswordAuthenticatedUserInterface
     */
    public function getPassword(): string
    {
        return $this->password;
    }

    public function setPassword(string $password): static
    {
        $this->password = $password;

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function eraseCredentials(): void
    {
        // If you store any temporary, sensitive data on the user, clear it here
        // $this->plainPassword = null;
    }
}

templates/fitness/form.html.twig
{% extends 'base.html.twig' %}

{% block body %}
    <div>
        <h2>Fitness Tracking: Enter Activity</h2>
    </div>

    <div >
        <div>
            {% for type, messages in app.flashes %}
                {% for message in messages %}
                    <div class="{{ type }}">
                        <strong>{{ type|capitalize }}!</strong> {{ message }}
                    </div>
                {% endfor %}
            {% endfor %}
            {{ form_start(form) }}
            <div>
                <div>
                    {{ form_row(form.activityType) }}
                </div>
                <div>
                    {{ form_row(form.distance) }}
                </div>
                <div>
                    {{ form_row(form.distanceUnit) }}
                </div>
                <div>
                    {{ form_row(form.elapsedTime) }} <span style="font-size:10px;">(In Minutes)</span>
                </div>
            </div>

            <hr>

            {{ form_row(form.save) }}

            {{ form_end(form) }}
        </div>
    </div>
{% endblock %}

{% block javascripts %}
    {{ parent() }}
    {{ encore_entry_script_tags('pages/post') }}
{% endblock %}

templates/fitness/list.html.twig
{% extends 'base.html.twig' %}

{% block body %}
    <div>
        <h2>Fitness Tracking: Dashboard</h2>
    </div>

    <div  class="parent"> {% for activityTypeTotalTime in activityTypeTotalTimes %}
        <div class="child">
            <div class="numberCircle" >{{ activityTypeTotalTime.totalTime }}</div><div style="font-size: 16px; color: green">{{activityTypeTotalTime.activityType}} (In Minutes)</div>  </div>
        {% endfor %}
    </div>
    <div >
        <div style="width:400px; background-color: #666666; padding: 40px; margin: 10px;">
            <form id="faq_search" action="{{ path('activity') }}" method="post">

                <select name="activity_type">
                    <option value="" selected>Select an Activity Type</option>
                    <option value="walking">walking</option>
                    <option value="running">running</option>
                    <option value="cycling">cycling</option>
                </select>
                <br><br>
                <button type="submit" class="button">Search</button>
            </form>
        </div>
        <div>
            <table width="100%">
                <thead>

                    <tr>
                        <th>Activity Type</th>
                        <th>Distance</th>
                        <th>Distance Unit</th>
                        <th>Elapsed Time</th>
                        <th>Activity Time</th>
                    </tr>

                    </thead>
                    <tbody>
                    {% for activity in activities %}
                    <tr>
                        <td>{{ activity.activityType }}</td>
                        <td>{{ activity.distance }}</td>
                        <td>{{ activity.distanceUnit }}</td>
                        <td>{{ activity.elapsedTime }}</td>
                        <td>{{ activity.activityDate | date('Y-m-d h:m:s') }}</td>

                    </tr>
                    {% endfor %}
                </table>

        </div>
    </div>
{% endblock %}